### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#10]
As a **Site User** I can **register an account** so that **I can comment on posts**

## Acceptance Criteria
- Register button should be visible on the homepage.
- When clicked I should be taken to the signup page.
- When I fill in my details and click submit a new account should be created.
- I should be notified that I have been logged in.

## Tasks
- [ ] Add register link to navbar and home page
- [ ]  Create message to notify user of successful signup
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
