### ISSUE TITLE
USER STORY:  Add Post

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#12]
As a **Admin** I can *add a post** so that **I can review something and give feedback**

## Acceptance Criteria
-Must be staff to post
- Be able at add a post content
- Be able to attach a featured image

## Tasks
- [ ] Create post form with required fields
- [ ] link with summernote
- [ ] Create html template for add post
- [ ] Create link to access add post
- [ ] Connect urls
- [ ] Test the completed functionality
