### ISSUE TITLE
USER STORY:  Edit Post

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#13]
As a **Admin** I can **edit posts** so that **I can update content**

## Acceptance Criteria
- User must be admin/staff to edit post

## Tasks
- [ ] Create view code
- [ ] Create html template for update post
- [ ] Create link to access update post
- [ ] Connect the urls
- [ ] Test the completed functionality
