### ISSUE TITLE
USER STORY:  Delete Post

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#14]
As a **Admin** I can **delete a post** so that **discard of post if inclined**

## Acceptance Criteria
- User must be admin/ staff to delete post
- User should have to confirm before deleting their post

## Tasks
- [ ]  Create view code
- [ ] Create html template for delete post
- [ ]  Create link to access delete post
- [ ] Connect the urls
- [ ] Test the completed functionality
