### ISSUE TITLE
USER STORY: Comment on Post

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#15]
As a **Site User** I can **leave a comment on posts** so that **I can give feedback and interact**

## Acceptance Criteria
- Registered and logged in users will be able to leave comments on posts
- User name and date should be visible together with the comment

## Tasks
- [ ] Create comment form with body field
- [ ]  Create view code
- [ ] Create link to submit comment
- [ ]  Connect urls
- [ ]  Test the completed functionality
