### ISSUE TITLE
USER STORY: View Post

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#16]
As a **Site User** I can **click on post title to view a post** so that **I can read the full content of the post, and read the comments**

## Acceptance Criteria
- User must click on a post from the home page

## Tasks
- [ ] Post title must double as a link to view the full post
- [ ] redirect from home page to the post detail page 
- [ ] test that it works
