### ISSUE TITLE
USER STORY:  Category

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#17]
As a **Site User** I can **navigate through the category list** so that **I can see the content specific to my interests**

## Acceptance Criteria
- Have a drop down menu to choose category

## Tasks
- [ ] Add a bootstrap dropdown menu
- [ ] Create three categories in the admin
- [ ] Test the functionality
