### ISSUE TITLE
USER STORY: Login/ Logout

### ISSUE THREAD

**Issue by stevekelly27** [stevekelly27/guitar_garage#9]
As a **Site User** I can **login or logout** so that **I can comment on posts**

## Acceptance Criteria
-  The sign in button should be visible on the home page and on the nav bar.
- When I click the button I should be taken to the log-in page.
- When I fill in my details and click submit I should be logged in.
-  I should then be notified that I have been logged in successfully.

## Tasks
- [ ] Add log in and log out links to navbar
- [ ] Customise allauth login, logout HTML templates
- [ ] Create success messages for successful login/logout
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
